name: noteflow
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc:
  equatable:
  firebase_core: ^3.4.1
  firebase_crashlytics: ^4.1.1
  firebase_auth: ^5.2.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.1
  image_picker: ^1.1.2
  firebase_storage: ^12.3.0
  font_awesome_flutter: ^10.7.0
  lottie: ^3.1.2
  hive:
  curved_navigation_bar: ^1.0.6
  hive_flutter:
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  get_it:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

